---
- import_playbook: setup-vm.yaml

- hosts: vm
  user: root
  become: yes
  vars:
    ipadm_password: "SECret.123"
    ipaadmin_password: "SECret.123"
    ipaserver_realm: "TEST.LOCAL"
    ipaserver_domain: "test.local"
    ipaserver_setup_dns: true
    ipaserver_auto_forwarders: true
  pre_tasks:
    - name: Set fully-qualified hostname
      hostname:
        name: "{{ img_name }}.{{ ipaserver_domain }}"
        use: systemd

  roles:
    - role: ipaserver
      state: present
    - role: ipa-server
