---
- hosts: 127.0.0.1
  connection: local
  
  roles:
    - role: common
      vars:
        rhel_version: "{{ rhel }}"
        img_name: "{{ name_ }}"
        base_img: "{{ image }}"
        ssh_key: "{{ key_file }}"
        repo_file: "./roles/common/files/redhat-{{rhel}}.repo"