---
- hosts: localhost
  connection: local
  gather_facts: yes
  pre_tasks:
    - name: Check if KVM {{ img_name }} with IP exists
      shell:
        cmd: virsh domifaddr "{{ img_name }}" 2>/dev/null  | grep -o -E "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.?)){4}"
      ignore_errors: true
      register: ip_addr

  roles:
    - role: check-image
    - role: common
      when: ip_addr.stdout == ""

  tasks:
    - name: Add existing VM to an inventory
      add_host:
        name: vm
        ansible_host: "{{ ip_addr.stdout }}"
        ansible_ssh_private_key_file: "{{ ssh_key }}"
      when:  ip_addr.stdout != ""

- hosts: vm
  tasks:
  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest
