---
# defaults file for common
rhel_version: "8.6"
home_dir: "{{ lookup('env', 'HOME') }}"
img_name: "rhel-{{ rhel_version }}"
os_dir: "{{ home_dir }}/os_dir"
base_img: "{{ os_dir }}/rhel-{{ rhel_version }}"
img_path: "{{ os_dir }}/{{ img_name }}.qcow2"
ssh_key: "{{ home_dir }}/.ssh/{{ ansible_user_id }}"
repo_file: "{{ role_path }}/files/redhat-{{ rhel_version }}.repo"
