---
# defaults file for common
rhel: "8.6"
home_dir: "{{ lookup('env', 'HOME') }}"
name_: "rhel-guest-image-8.6-1200"
image: "{{ home_dir }}/os_dir/rhel-{{ rhel }}.qcow2"
key_file: "{{ home_dir }}/.ssh/{{ name_ }}-rhel-{{ rhel }}"
img_path: "{{ home_dir }}/os_dir/{{ name_ }}.qcow2"
