---
# defaults file for common
rhel: "8.6"
name_: "rhel-guest-image-8.6-1200"
image: "/home/pyadlous/os_dir/{{ name_ }}.x86_64.qcow2" 
key_file: "{{ name_ }}-rhel-{{ rhel }}"
img_path: "/home/pyadlous/os_dir/{{ name_ }}.qcow2"