---
# defaults file for common
rhel: "8.6"
home_dir: "{{ lookup('env', 'HOME') }}"
name_: "rhel-{{ rhel }}"
image: "{{ home_dir }}/os_dir/rhel-{{ rhel }}"
key_file: "{{ home_dir }}/.ssh/{{ ansible_user_id }}"
img_path: "{{ home_dir }}/os_dir/{{ name_ }}.qcow2"
