---
- name: Copy configuration file for SCAutolib
  copy:
    src: "{{ conf_file_path }}"
    dest: /root/conf.json

- name: Run prepare command
  shell:
    cmd: scauto --force --conf /root/conf.json prepare --gdm --install-missing

- name: Set default target to graphical.target
  shell: systemctl set-default graphical.target

- name: Set eth0 device to autoconnect after reboot
  shell: nmcli device set eth0  autoconnect yes

- name: Reboot the system
  reboot:
