---
- name: Upgrade the system
  dnf:
    name: "*"
    state: latest
    update_cache: yes
    update_only: yes

- name: Install "Smart Card Support" group
  dnf:
    name: "@Smart Card Support"
    state: present

- name: Install additional packages
  dnf:
    name:
      - python3
      - python3-pip
      - vim
      - sssd
      - sssd-tools
      - gnutls-utils
      - gdm
    state: latest

#- name: Install "Server with GUI" group
#  dnf:
#    name: "@Server with GUI"
#    state: present

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Remove packates not needed anymore
  dnf:
    autoremove: yes

- name: Create directory {{ item }}
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - '/root/SCAutolib'
    - '/root/SC-tests'
    - '/root/smart-cards'

- name: Mount an NFS SCAutolib
  ansible.posix.mount:
    src: "{{ item.export }}"
    path: "{{ item.mountpoint }}"
    opts: "rw"
    state: mounted
    fstype: nfs
  loop:
    - { mountpoint: '/root/SCAutolib', export: "192.168.122.1:{{ home_dir }}/work/crypto/SCAutolib" }
    - { mountpoint: '/root/SC-tests', export: "192.168.122.1:{{ home_dir }}/work/crypto/tests/SC-tests" }
    - { mountpoint: '/root/smart-cards', export: "192.168.122.1:{{ home_dir }}/work/crypto/tests/smart-cards" }
  ignore_errors: true

- name: Link SCAutolib for imports to Python user-site directory
  shell:
    cmd: "mkdir -p $(python3 -m site --user-site) && ln -sf /root/SCAutolib $(python3 -m site --user-site)"
    warn: false

- name: Install SCAutolib requirements
  pip:
    requirements: "/root/SCAutolib/src/env/requirements.txt"
    extra_args: --upgrade -I

- name: Install SC test requirements
  pip:
    requirements: "/root/SC-tests/requirements.txt"
    extra_args: --upgrade -I

- name: Copy configuraiong file for SCAutolib to remote
  copy:
    src: ../files/configuration.yaml
    dest: /root/configuration.yaml

- name: Update configuraiong file for SCAutolib
  replace:
    path: /root/configuration.yaml
    regexp: "{{ item.ptrn }}"
    replace: "{{ item.new }}"
  loop:
    - { ptrn: "<server_ip>", new: "{{ server_ip }}" }
    - { ptrn: "<server_name>", new: "{{ server_name }}.{{ domain }}" }
    - { ptrn: "<client_name>", new: "{{ client_name }}.{{ domain }}" }
    - { ptrn: "<domain>", new: "{{ domain }}" }
    - { ptrn: "<realm>", new: "{{ realm }}" }
    - { ptrn: "<admin_passwd>", new: "{{ admin_passwd }}" }
    - { ptrn: "<ipa_user_passwd>", new: "{{ ipa_user_passwd }}" }
    - { ptrn: "<ipa_username>", new: "{{ ipa_username }}" }

- name: Run prepare command
  shell:
    cmd: python3 /root/SCAutolib/src/env_cli.py prepare --ca --ipa --cards -m --conf /root/configuration.yaml
