---
- name: Check image name
  stat:
    path: "{{ img_path }}"
  register: img_stat_result

- name: Copy image
  copy:
    src: "{{ base_img }}"
    dest: "{{ img_path }}"
  when: not img_stat_result.stat.exists

- name: Check SSh key
  stat:
    path: "{{ssh_key}}"
  register: stat_result

- name: Generate key
  openssh_keypair:
    path: "{{ ssh_key }}"
    type: rsa
    size: 4096
    state: present
    force: no
  when: not stat_result.stat.exists

- name: Check repo file
  file:
    path: "{{ repo_file }}"
    state: file

- name: Prepare VM (virt-sysprep)
  shell:
    cmd: |
      virt-sysprep --uninstall cloud-init \
          --selinux-relabel \
          --root-password password:redhat \
          --ssh-inject root:file:"{{ ssh_key }}.pub" \
          --upload "{{ repo_file }}":/etc/yum.repos.d/redhat.repo \
          -a "{{ img_path }}" \
          -c qemu:///system

- name: Install VM (virt-install)
  shell:
    cmd: |
      virt-install --connect qemu:///system --import --memory 2048 --vcpus 2 --noautoconsole --os-variant rhel-unknown \
                   --name "{{ img_name }}" --check all=off --disk path="{{ img_path }}" 

- name: Get "{{ img_name }}" IP address
  shell: virsh domifaddr "{{ img_name }}"  | grep -o -E "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.?)){4}"
  register: ip_addr
  until: ip_addr.stdout | ipaddr
  retries: 10
  delay: 6

- name: Create initial snapshot
  shell: virsh snapshot-create-as --domain "{{ img_name }}" --name "initial"

- name: Add "{{ img_name }}" to SSH config file
  blockinfile:
    path: /home/{{ ansible_user_id }}/.ssh/config
    backup: yes
    block: |
      Host {{ img_name }}
        Hostname {{ ip_addr.stdout }}
        Preferredauthentications publickey
        User root
        UserKnownHostsFile /dev/null
        StrictHostKeyChecking no
        IdentityFile {{ key_file }}

- name: Add VM to inventory
  add_host:
      name: vm
      ansible_host: "{{ ip_addr.stdout }}"